version: "3"

services:
  db:
    env_file:
      - ./.env
    image: postgres:latest
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_HOST=${SQL_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    env_file:
      - ./.env
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/david_langr/
    command: python manage.py runserver 0.0.0.0:${PORT}
    depends_on:
      - db
volumes:
  postgres_data: