# Generated by Django 4.0.4 on 2022-05-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Celé jméno', max_length=255, null=True)),
                ('email', models.CharField(blank=True, help_text='Email', max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ulice')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Město')),
                ('zip', models.CharField(blank=True, max_length=32, null=True, verbose_name='PSČ')),
                ('facebook', models.URLField(blank=True, help_text='Your Facebook page URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Your Instagram page URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Your LinkedIn page URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Your Twitter page URL', null=True)),
                ('dark_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Logo pro tmavé pozadí')),
                ('favicon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Favicona')),
                ('favicon_apple', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Favicona pro apple')),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Globální nastavení',
            },
        ),
    ]
