# Generated by Django 4.0.4 on 2022-05-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_mysettings_dark_logo_alter_mysettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysettings',
            name='ico',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='IČO'),
        ),
    ]
