# Generated by Django 4.0.4 on 2022-05-24 17:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('first_section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Jméno a příjmení', max_length=60, required=False)), ('sub_heading', wagtail.blocks.CharBlock(label='Podnadpis', max_length=80, required=False))])), ('about_section', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Nadpis', max_length=60, required=False)), ('sub_heading', wagtail.blocks.CharBlock(label='Podnadpis', max_length=160, required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='profilová fotka', required=True)), ('position_name', wagtail.blocks.CharBlock(label='Název pozice', max_length=80, required=False)), ('birthday', wagtail.blocks.CharBlock(label='datum narození', max_length=80, required=False)), ('address', wagtail.blocks.CharBlock(label='adresa', max_length=80, required=False)), ('email', wagtail.blocks.CharBlock(label='email', max_length=80, required=False)), ('freelance_status', wagtail.blocks.CharBlock(label='status', max_length=80, required=False)), ('text', wagtail.blocks.TextBlock(help_text='zobrazí se pod základníma údajema', label='text k o mě sekci', required=False))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
