# Generated by Django 4.0.4 on 2022-05-29 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('main', '0006_contactform_alter_formfield_page_delete_contactpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactBlock',
        ),
    ]
