# Generated by Django 4.0.4 on 2022-06-13 19:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('main', '0009_blogpagerelatedlink_delete_blogdetailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('custom_title', models.CharField(max_length=100)),
                ('text', wagtail.fields.RichTextField(blank=True, verbose_name='Text článku')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Obrázek článku')),
            ],
            options={
                'verbose_name': 'Detailní stránka článku',
                'verbose_name_plural': 'Detailní stránky článků',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='BlogPageRelatedLink',
        ),
    ]
